env:
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
overrides: []
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
  - "check-file"
rules:
  "@typescript-eslint/no-explicit-any": "off"
  "check-file/filename-naming-convention":
    - error
    - "src/**/*.{ts,tsx}": CAMEL_CASE
